apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myhelm
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: myFirstHelmChart
    repoURL: 'https://github.com/IshwarKhadka000/myfirsthelmchart.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
